lang = {
	menu_sensecityapp:"SENSE.CITY APP",
	menu_participation:"PARTICIPATION",
	menu_data:"DATA",
	menu_contact:"CONTACT",
	menu_about:"ABOUT",
	msg_header:"Active participation for my city!", 
	msg_happen_in_city:"What's happening in the city?", 
	msg_partcipate:"My participation", 
	msg_start_now:"Start now", 
	msg_start_now_text:"You can report issues through our available Sense.City mobile apps or from your PC browser", 
	msg_start_now_webbrowser:"Web browser", 
	msg_start_now_android:"Android Device", 
	msg_start_now_ios: "iOS Device", 
	msg_start_now_windows:"Windows Device", 
	msg_how_partcipate:"My participation", 
	msg_anafora_probl:"Report issues", 
	msg_anafora_probl_text:"You are the city sensors! By using Sense.City's mobile apps you communicate to your fellow citizens issues that you experience everyday in your city.", 
	msg_astiki_summe:"en Αστική συμμετοχή", 
	msg_astiki_summe_text:"en Συμμετέχετε ενεργά στις διαδικασίες και στην επίλυση προβλημάτων που αφορούν τη ζωή σας στη πόλη. Βοηθήστε στην αστική ανάπτυξη και στην καλύτερη σχέση μεταξύ πολιτών και φορέων της πόλης.", 
	msg_syn_dimiourg:"en Συν-δημιουργία", 
	msg_syn_dimiourg_text:"en Η πλατφόρμα sense.city προσπαθεί να βάλει τα εργαλεία για την ενεργοποίηση των πολιτών, τη δημιουργικότητα, το σχεδιασμό και την επικοινωνία στα χέρια του καθενός και καλεί για συλλογική σκέψη και δράσεις τόσο τους πολίτες όσο και τους φορείς της πόλης.", 
	msg_sec_dedomena:"en Δεδομένα", 
	msg_eukoli_xrisi:"en Εύκολη χρήση", 
	msg_eukoli_xrisi_text:"en Απλά χρησιμοποιώντας την εφαρμογή sense.city στο κινητό σας, γίνεστε αισθητήρας της πόλης με ένα κλικ!", 
	msg_anonymia:"en Ανώνυμα", 
	msg_anonymia_text:"en Η εφαρμογή στέλνει ανώνυμα το γεγονός που θέλετε να καταγραφεί.", 
	msg_free_serv:"en Δωρεάν", 
	msg_free_serv_text:"en Δεν υπάρχει κάποια χρέωση για την υπηρεσία. (Προσoχή στην ογκοχρέωση των δεδομένων κινητής τηλεφωνίας)", 
	msg_open_data:"en Ανοιχτά δεδομένα", 
	msg_open_data_text:"en Προσφέρουμε ένα ανοιχτό API για προγραμματιστές και όποιον ενδιαφέρεται να χρησιμοποιήσει τη πλατφόρμα sense.city. Δείτε περισσότερα εδώ: <a href=\"https://github.com/sensecitycode/sensecity-api/blob/master/README.md\">apidoc</a>", 
	msg_developers_sec:"en Developers", 
	msg_developers_sec_text:"en Αν θέλετε να βοηθήσετε στην αναπτυξη ή να δειτε το κώδικα: <a href=\"https://github.com/sensecitycode/sensecity-api\">API</a>", 
	msg_section_contact:"Επικοινωνία", 
	msg_section_contact_text1:"en Αγαπάμε την επικοινωνία μαζί σας! <br />", 
	msg_section_contact_text2:"en Αποστείλατε email στο <a href=\"mailto:info@sense.city\" style=\"color: #000000;\">info@sense.city</a> και το συντομότερο δυνατό θα επικοινωνήσουμε μαζί σας.", 
	msg_section_info:"en Πληροφορίες", 
	msg_section_followus:"en Ακολουθήστε μας", 
	msg_popup_title:"sense.city", 
	msg_popup_msg:"en Συμμετέχω ενεργά στη πόλη μου", 
	msg_popup_text:"en Οι πολίτες είστε οι αισθητήρες της πόλης! Χρησιμοποιώντας τις δικές σας συσκευές επικοινωνίας, είτε μέσω της εφαρμογής sense.city είτε με άλλες συσκευές που αναφέρουν στο sense.city δεδομένα της πόλης, ενημερώνετε τους συμπολίτες και το δήμο για προβλήματα και συμβάντα που συμβαίνουν κάθε στιγμή."
};
