lang = {
	menu_sensecityapp:"SENSE.CITY APP",
	menu_participation:"ΣΥΜΜΕΤΟΧΗ",
	menu_data:"ΔΕΔΟΜΕΝΑ",
	menu_contact:"ΕΠΙΚΟΙΝΩΝΙΑ",
	menu_about:"ΣΧΕΤΙΚΑ",
	msg_header:"Συμμετέχω ενεργά στη πόλη μου",
	msg_happen_in_city:"Τι συμβαίνει στη πόλη",
	msg_partcipate:"Πώς συμμετέχω", 
	msg_start_now:"Ξεκινήστε τώρα", 
	msg_start_now_text:"Μπορείτε να αναφέρετε προβλήματα από το κινητό σας με τις εφαρμογές που είναι διαθέσιμες αλλά και από τον προσωπικό σας υπολογιστή μέσω του sense.city website", 
	msg_start_now_webbrowser:"Web browser", 
	msg_start_now_android:"Συσκευές Android", 
	msg_start_now_ios: "Συσκευές iOS", 
	msg_start_now_windows:"Συσκευές Windows", 
	msg_how_partcipate:"Πώς συμμετέχω", 
	msg_anafora_probl:"Αναφορά προβλημάτων", 
	msg_anafora_probl_text:"Οι πολίτες είστε οι αισθητήρες της πόλης! Χρησιμοποιώντας τις δικές σας συσκευές επικοινωνίας, είτε μέσω της εφαρμογής sense.city είτε με άλλες συσκευές που αναφέρουν στο sense.city δεδομένα της πόλης, ενημερώνετε τους συμπολίτες και το δήμο για προβλήματα και συμβάντα που συμβαίνουν κάθε στιγμή", 
	msg_astiki_summe:"Αστική συμμετοχή", 
	msg_astiki_summe_text:"Συμμετέχετε ενεργά στις διαδικασίες και στην επίλυση προβλημάτων που αφορούν τη ζωή σας στη πόλη. Βοηθήστε στην αστική ανάπτυξη και στην καλύτερη σχέση μεταξύ πολιτών και φορέων της πόλης.", 
	msg_syn_dimiourg:"Συν-δημιουργία", 
	msg_syn_dimiourg_text:"Η πλατφόρμα sense.city προσπαθεί να βάλει τα εργαλεία για την ενεργοποίηση των πολιτών, τη δημιουργικότητα, το σχεδιασμό και την επικοινωνία στα χέρια του καθενός και καλεί για συλλογική σκέψη και δράσεις τόσο τους πολίτες όσο και τους φορείς της πόλης.", 
	msg_sec_dedomena:"Δεδομένα", 
	msg_eukoli_xrisi:"Εύκολη χρήση", 
	msg_eukoli_xrisi_text:"Απλά χρησιμοποιώντας την εφαρμογή sense.city στο κινητό σας, γίνεστε αισθητήρας της πόλης με ένα κλικ!", 
	msg_anonymia:"Ανώνυμα", 
	msg_anonymia_text:"Η εφαρμογή στέλνει ανώνυμα το γεγονός που θέλετε να καταγραφεί.", 
	msg_free_serv:"Δωρεάν", 
	msg_free_serv_text:"Δεν υπάρχει κάποια χρέωση για την υπηρεσία. (Προσoχή στην ογκοχρέωση των δεδομένων κινητής τηλεφωνίας)",
	msg_open_data:"Ανοιχτά δεδομένα", 
	msg_open_data_text:"Προσφέρουμε ένα ανοιχτό API για προγραμματιστές και όποιον ενδιαφέρεται να χρησιμοποιήσει τη πλατφόρμα sense.city. Δείτε περισσότερα εδώ: <a href=\"https://github.com/sensecitycode/sensecity-api/blob/master/README.md\">apidoc</a>", 
	msg_developers_sec:"Developers", 
	msg_developers_sec_text:"Αν θέλετε να βοηθήσετε στην αναπτυξη ή να δειτε το κώδικα: <a href=\"https://github.com/sensecitycode/sensecity-api\">API</a>", 
	msg_section_contact:"Επικοινωνία", 
	msg_section_contact_text1:"Αγαπάμε την επικοινωνία μαζί σας! <br />", 
	msg_section_contact_text2:"Αποστείλατε email στο <a href=\"mailto:info@sense.city\" style=\"color: #000000;\">info@sense.city</a> και το συντομότερο δυνατό θα επικοινωνήσουμε μαζί σας.", 
	msg_section_info:"Πληροφορίες", 
	msg_section_followus:"Ακολουθήστε μας", 
	msg_popup_title:"sense.city @ Πάτρα", 
	msg_popup_msg:"Συμμετέχω ενεργά στη πόλη μου",
	msg_popup_text:"Οι πολίτες είστε οι αισθητήρες της πόλης! Χρησιμοποιώντας τις δικές σας συσκευές επικοινωνίας, είτε μέσω της εφαρμογής sense.city είτε με άλλες συσκευές που αναφέρουν στο sense.city δεδομένα της πόλης, ενημερώνετε τους συμπολίτες και το δήμο για προβλήματα και συμβάντα που συμβαίνουν κάθε στιγμή.",
	msg_subdomain_title:"Τι συμβαίνει στην πόλη",
	msg_sub_text1:"Δείτε με μια ματιά εδώ τι έχουν αναφέρει οι υπόλοιποι πολίτες και ποια είναι τα τελευταία συμβάντα στη πόλη!",
	msg_sub_text2:"* Η απεικόνιση των κάδων απορριμάτων δεν συνάδει με οποιαδήποτε οριστική χωροθέτηση αυτών.",
	msg_dilosi:"Δήλωση",
	msg_anathesi:"Ανάθεση",
	msg_complete:"Ολοκληρώθηκε",
	msg_label_long:"Γεωγραφικό Μήκος",
	msg_label_lat:"Γεωγραφικό Πλάτος",
	msg_label_type:"Τύπος προβλήματος",
	msg_type_select:"Επιλέξτε τύπο προβλήματος",
	msg_type_garbage:"Σκουπίδια",
	msg_type_lighting:"Φωτισμός",
	msg_type_plumbing:"Ύδρευση",
	msg_type_road:"Οδόστρωμα",
	msg_problem_detail:"Προβλήμα",
	msg_perigrafi_problem:"Περιγραφή",
	msg_photograph:"Φωτογραφία",
	msg_submit_btn:"Αποστολή"
};
